// Run this script once to seed the Bank table with data
// Execute in your Supabase SQL Editor

const List<Map<String, dynamic>> BANK_DATA = [
  // Local Banks
  {
    'bankId': 'LOCAL_AFFIN',
    'bankName': 'Affin Bank',
    'bankType': 'Local',
    'bankIcon': 'AFFINBANK.png',
  },
  {
    'bankId': 'LOCAL_ALLIANCE',
    'bankName': 'Alliance Bank',
    'bankType': 'Local',
    'bankIcon': 'ALLIANCEBANK.png',
  },
  {
    'bankId': 'LOCAL_AM',
    'bankName': 'AM Bank',
    'bankType': 'Local',
    'bankIcon': 'AMBANK.png',
  },
  {
    'bankId': 'LOCAL_CIMB',
    'bankName': 'CIMB Bank',
    'bankType': 'Local',
    'bankIcon': 'CIMBBANK.png',
  },
  {
    'bankId': 'LOCAL_HLB',
    'bankName': 'Hong Leong Bank',
    'bankType': 'Local',
    'bankIcon': 'HONGLEONGBANK.png',
  },
  {
    'bankId': 'LOCAL_MAYBANK',
    'bankName': 'Maybank',
    'bankType': 'Local',
    'bankIcon': 'MAYBANK.png',
  },
  {
    'bankId': 'LOCAL_PUBLICBANK',
    'bankName': 'Public Bank',
    'bankType': 'Local',
    'bankIcon': 'PUBLICBANK.png',
  },
  {
    'bankId': 'LOCAL_RHB',
    'bankName': 'RHB',
    'bankType': 'Local',
    'bankIcon': 'RHB.png',
  },

  // Islamic Banks
  {
    'bankId': 'ISLAMIC_AFFIN',
    'bankName': 'Affin Islamic Bank',
    'bankType': 'Islamic',
    'bankIcon': 'AffinIslamicBank.png',
  },
  {
    'bankId': 'ISLAMIC_ALLIANCE',
    'bankName': 'Alliance Islamic Bank',
    'bankType': 'Islamic',
    'bankIcon': 'AllianceIslamicBank.png',
  },
  {
    'bankId': 'ISLAMIC_AMBANK',
    'bankName': 'AmBank Islamic',
    'bankType': 'Islamic',
    'bankIcon': 'AmBankIslamic.png',
  },
  {
    'bankId': 'ISLAMIC_BANKISLAM',
    'bankName': 'Bank Islam',
    'bankType': 'Islamic',
    'bankIcon': 'bankIslam.png',
  },
  {
    'bankId': 'ISLAMIC_MUAMALAT',
    'bankName': 'Bank Muamalat',
    'bankType': 'Islamic',
    'bankIcon': 'BankMuamalat.png',
  },
  {
    'bankId': 'ISLAMIC_CIMB',
    'bankName': 'CIMB Islamic',
    'bankType': 'Islamic',
    'bankIcon': 'CIMBIslamic.png',
  },
  {
    'bankId': 'ISLAMIC_HLB',
    'bankName': 'Hong Leong Islamic',
    'bankType': 'Islamic',
    'bankIcon': 'HongLeongIslamic.jpg',
  },
  {
    'bankId': 'ISLAMIC_MAYBANK',
    'bankName': 'Maybank Islamic',
    'bankType': 'Islamic',
    'bankIcon': 'MaybankIslamic.png',
  },
  {
    'bankId': 'ISLAMIC_PUBLICBANK',
    'bankName': 'Public Islamic Bank',
    'bankType': 'Islamic',
    'bankIcon': 'PublicIslamicBank.png',
  },
  {
    'bankId': 'ISLAMIC_RHB',
    'bankName': 'RHB Islamic Bank',
    'bankType': 'Islamic',
    'bankIcon': 'RHBIslamicBank.jpg',
  },

  // Foreign Banks
  {
    'bankId': 'FOREIGN_ABC',
    'bankName': 'Agricultural Bank of China',
    'bankType': 'Foreign',
    'bankIcon': 'AgriculturalBankofChina.png',
  },
  {
    'bankId': 'FOREIGN_BOA_MY',
    'bankName': 'Bank of America Malaysia',
    'bankType': 'Foreign',
    'bankIcon': 'BankofAmericaMalaysia.png',
  },
  {
    'bankId': 'FOREIGN_BOC',
    'bankName': 'Bank of China',
    'bankType': 'Foreign',
    'bankIcon': 'BankofChina.png',
  },
  {
    'bankId': 'FOREIGN_BOCM',
    'bankName': 'Bank of Communication',
    'bankType': 'Foreign',
    'bankIcon': 'BankOfCommunication.png',
  },
  {
    'bankId': 'FOREIGN_BARCLAYS',
    'bankName': 'Barclays Bank',
    'bankType': 'Foreign',
    'bankIcon': 'BarclaysBank.png',
  },
  {
    'bankId': 'FOREIGN_BNPPARIBAS',
    'bankName': 'BNP Paribas Malaysia',
    'bankType': 'Foreign',
    'bankIcon': 'BNPParibasMalaysia.png',
  },
  {
    'bankId': 'FOREIGN_BNYMELLON',
    'bankName': 'BNY Mellon',
    'bankType': 'Foreign',
    'bankIcon': 'BNYMellon.png',
  },
  {
    'bankId': 'FOREIGN_CCB',
    'bankName': 'CCB Bank',
    'bankType': 'Foreign',
    'bankIcon': 'CCBBank.png',
  },
  {
    'bankId': 'FOREIGN_CITIBANK',
    'bankName': 'Citibank',
    'bankType': 'Foreign',
    'bankIcon': 'Citibank.png',
  },
  {
    'bankId': 'FOREIGN_COMMERZBANK',
    'bankName': 'Commerzbank',
    'bankType': 'Foreign',
    'bankIcon': 'Commerzbank.png',
  },
  {
    'bankId': 'FOREIGN_CREDITAGRICOLE',
    'bankName': 'Credit Agricole',
    'bankType': 'Foreign',
    'bankIcon': 'CreditAgricole.png',
  },
  {
    'bankId': 'FOREIGN_DBS',
    'bankName': 'DBS Bank',
    'bankType': 'Foreign',
    'bankIcon': 'DBSBank.png',
  },
  {
    'bankId': 'FOREIGN_DEUTSCHEBANK',
    'bankName': 'Deutsche Bank',
    'bankType': 'Foreign',
    'bankIcon': 'DeutscheBank.png',
  },
  {
    'bankId': 'FOREIGN_DBJAPAN',
    'bankName': 'Development Bank of Japan',
    'bankType': 'Foreign',
    'bankIcon': 'DevelopmentBankofJapan.png',
  },
  {
    'bankId': 'FOREIGN_GOLDMANSACHS',
    'bankName': 'Goldman Sachs',
    'bankType': 'Foreign',
    'bankIcon': 'GoldmanSachs.png',
  },
  {
    'bankId': 'FOREIGN_HSBC',
    'bankName': 'HSBC Bank',
    'bankType': 'Foreign',
    'bankIcon': 'HSBCBank.png',
  },
  {
    'bankId': 'FOREIGN_ICBC',
    'bankName': 'ICBC Bank',
    'bankType': 'Foreign',
    'bankIcon': 'ICBCBank.png',
  },
  {
    'bankId': 'FOREIGN_JPMORGAN',
    'bankName': 'J.P. Morgan Chase Bank',
    'bankType': 'Foreign',
    'bankIcon': 'J.P.MorganChaseBank.png',
  },
  {
    'bankId': 'FOREIGN_LLOYDS',
    'bankName': 'Lloyds Bank',
    'bankType': 'Foreign',
    'bankIcon': 'LloydsBank.png',
  },
  {
    'bankId': 'FOREIGN_MIZUHO',
    'bankName': 'Mizuho Bank',
    'bankType': 'Foreign',
    'bankIcon': 'MizuhoBank.png',
  },
  {
    'bankId': 'FOREIGN_MORGANSTANLEY',
    'bankName': 'Morgan Stanley',
    'bankType': 'Foreign',
    'bankIcon': 'MorganStanley.png',
  },
  {
    'bankId': 'FOREIGN_MUFG',
    'bankName': 'MUFG Bank',
    'bankType': 'Foreign',
    'bankIcon': 'MUFGBank.png',
  },
  {
    'bankId': 'FOREIGN_NATWEST',
    'bankName': 'NatWest Group',
    'bankType': 'Foreign',
    'bankIcon': 'NatWestGroup.png',
  },
  {
    'bankId': 'FOREIGN_OCBC',
    'bankName': 'Oversea Chinese Banking Corporation',
    'bankType': 'Foreign',
    'bankIcon': 'OverseaChineseBankingCorporation.webp',
  },
  {
    'bankId': 'FOREIGN_PNC',
    'bankName': 'PNC Bank',
    'bankType': 'Foreign',
    'bankIcon': 'PNCBank.png',
  },
  {
    'bankId': 'FOREIGN_SOCIETEGENERALE',
    'bankName': 'Societe Generale',
    'bankType': 'Foreign',
    'bankIcon': 'SociétéGénérale.png',
  },
  {
    'bankId': 'FOREIGN_STANDARDCHARTERED',
    'bankName': 'Standard Chartered Bank',
    'bankType': 'Foreign',
    'bankIcon': 'StandardCharteredBank.png',
  },
  {
    'bankId': 'FOREIGN_SUMITOMOMITSUI',
    'bankName': 'Sumitomo Mitsui Banking Corporation Malaysia',
    'bankType': 'Foreign',
    'bankIcon': 'SumitomoMitsuiBankingCorporationMalaysia.png',
  },
  {
    'bankId': 'FOREIGN_USBANK',
    'bankName': 'U.S. Bank',
    'bankType': 'Foreign',
    'bankIcon': 'U.S.Bank.png',
  },
  {
    'bankId': 'FOREIGN_UBS',
    'bankName': 'UBS',
    'bankType': 'Foreign',
    'bankIcon': 'UBS.png',
  },
  {
    'bankId': 'FOREIGN_UOB',
    'bankName': 'United Overseas Bank',
    'bankType': 'Foreign',
    'bankIcon': 'UnitedOverseasBank.png',
  },
  {
    'bankId': 'FOREIGN_WELLSFARGO',
    'bankName': 'Wells Fargo',
    'bankType': 'Foreign',
    'bankIcon': 'WellsFargo.png',
  },
];
