/// Currency seed data for initial database population
class CurrencySeedData {
  static const List<Map<String, String>> currencies = [
    {
      'currencyId': 'AFN',
      'name': 'Afghani',
      'symbol': 'AFN',
      'country': 'Afghanistan',
    },
    {'currencyId': 'ALL', 'name': 'Lek', 'symbol': 'ALL', 'country': 'Albania'},
    {
      'currencyId': 'DZD',
      'name': 'Algerian Dinar',
      'symbol': 'DZD',
      'country': 'Algeria',
    },
    {
      'currencyId': 'AOA',
      'name': 'Kwanza',
      'symbol': 'AOA',
      'country': 'Angola',
    },
    {
      'currencyId': 'ARS',
      'name': 'Argentine Peso',
      'symbol': 'ARS',
      'country': 'Argentina',
    },
    {
      'currencyId': 'AMD',
      'name': 'Armenian Dram',
      'symbol': 'AMD',
      'country': 'Armenia',
    },
    {
      'currencyId': 'AUD',
      'name': 'Australian Dollar',
      'symbol': 'AUD',
      'country': 'Australia',
    },
    {
      'currencyId': 'EUR',
      'name': 'Euro',
      'symbol': 'EUR',
      'country': 'Austria',
    },
    {
      'currencyId': 'AZN',
      'name': 'Azerbaijani Manat',
      'symbol': 'AZN',
      'country': 'Azerbaijan',
    },
    {
      'currencyId': 'BSD',
      'name': 'Bahamian Dollar',
      'symbol': 'BSD',
      'country': 'Bahamas',
    },
    {
      'currencyId': 'BHD',
      'name': 'Bahraini Dinar',
      'symbol': 'BHD',
      'country': 'Bahrain',
    },
    {
      'currencyId': 'BDT',
      'name': 'Taka',
      'symbol': 'BDT',
      'country': 'Bangladesh',
    },
    {
      'currencyId': 'BBD',
      'name': 'Barbados Dollar',
      'symbol': 'BBD',
      'country': 'Barbados',
    },
    {
      'currencyId': 'BYN',
      'name': 'Belarusian Ruble',
      'symbol': 'BYN',
      'country': 'Belarus',
    },
    {
      'currencyId': 'BZD',
      'name': 'Belize Dollar',
      'symbol': 'BZD',
      'country': 'Belize',
    },
    {
      'currencyId': 'XOF',
      'name': 'West African CFA Franc',
      'symbol': 'XOF',
      'country': 'Benin',
    },
    {
      'currencyId': 'BTN',
      'name': 'Ngultrum',
      'symbol': 'BTN',
      'country': 'Bhutan',
    },
    {
      'currencyId': 'BOB',
      'name': 'Boliviano',
      'symbol': 'BOB',
      'country': 'Bolivia',
    },
    {
      'currencyId': 'BAM',
      'name': 'Convertible Mark',
      'symbol': 'BAM',
      'country': 'Bosnia and Herzegovina',
    },
    {
      'currencyId': 'BWP',
      'name': 'Pula',
      'symbol': 'BWP',
      'country': 'Botswana',
    },
    {
      'currencyId': 'BRL',
      'name': 'Brazilian Real',
      'symbol': 'BRL',
      'country': 'Brazil',
    },
    {
      'currencyId': 'BND',
      'name': 'Brunei Dollar',
      'symbol': 'BND',
      'country': 'Brunei',
    },
    {
      'currencyId': 'BGN',
      'name': 'Bulgarian Lev',
      'symbol': 'BGN',
      'country': 'Bulgaria',
    },
    {
      'currencyId': 'BIF',
      'name': 'Burundian Franc',
      'symbol': 'BIF',
      'country': 'Burundi',
    },
    {
      'currencyId': 'KHR',
      'name': 'Riel',
      'symbol': 'KHR',
      'country': 'Cambodia',
    },
    {
      'currencyId': 'XAF',
      'name': 'Central African CFA Franc',
      'symbol': 'XAF',
      'country': 'Cameroon',
    },
    {
      'currencyId': 'CAD',
      'name': 'Canadian Dollar',
      'symbol': 'CAD',
      'country': 'Canada',
    },
    {
      'currencyId': 'CVE',
      'name': 'Cabo Verde Escudo',
      'symbol': 'CVE',
      'country': 'Cape Verde',
    },
    {
      'currencyId': 'CLP',
      'name': 'Chilean Peso',
      'symbol': 'CLP',
      'country': 'Chile',
    },
    {
      'currencyId': 'CNY',
      'name': 'Yuan Renminbi',
      'symbol': 'CNY',
      'country': 'China',
    },
    {
      'currencyId': 'COP',
      'name': 'Colombian Peso',
      'symbol': 'COP',
      'country': 'Colombia',
    },
    {
      'currencyId': 'KMF',
      'name': 'Comorian Franc',
      'symbol': 'KMF',
      'country': 'Comoros',
    },
    {
      'currencyId': 'CDF',
      'name': 'Congolese Franc',
      'symbol': 'CDF',
      'country': 'Congo (DRC)',
    },
    {
      'currencyId': 'CRC',
      'name': 'Costa Rican Colon',
      'symbol': 'CRC',
      'country': 'Costa Rica',
    },
    {
      'currencyId': 'CUP',
      'name': 'Cuban Peso',
      'symbol': 'CUP',
      'country': 'Cuba',
    },
    {
      'currencyId': 'CZK',
      'name': 'Czech Koruna',
      'symbol': 'CZK',
      'country': 'Czech Republic',
    },
    {
      'currencyId': 'DKK',
      'name': 'Danish Krone',
      'symbol': 'DKK',
      'country': 'Denmark',
    },
    {
      'currencyId': 'DJF',
      'name': 'Djiboutian Franc',
      'symbol': 'DJF',
      'country': 'Djibouti',
    },
    {
      'currencyId': 'DOP',
      'name': 'Dominican Peso',
      'symbol': 'DOP',
      'country': 'Dominican Republic',
    },
    {
      'currencyId': 'USD',
      'name': 'US Dollar',
      'symbol': 'USD',
      'country': 'United States',
    },
    {
      'currencyId': 'EGP',
      'name': 'Egyptian Pound',
      'symbol': 'EGP',
      'country': 'Egypt',
    },
    {
      'currencyId': 'ETB',
      'name': 'Ethiopian Birr',
      'symbol': 'ETB',
      'country': 'Ethiopia',
    },
    {
      'currencyId': 'FJD',
      'name': 'Fiji Dollar',
      'symbol': 'FJD',
      'country': 'Fiji',
    },
    {
      'currencyId': 'GEL',
      'name': 'Lari',
      'symbol': 'GEL',
      'country': 'Georgia',
    },
    {
      'currencyId': 'GHS',
      'name': 'Ghana Cedi',
      'symbol': 'GHS',
      'country': 'Ghana',
    },
    {
      'currencyId': 'GTQ',
      'name': 'Quetzal',
      'symbol': 'GTQ',
      'country': 'Guatemala',
    },
    {
      'currencyId': 'GNF',
      'name': 'Guinean Franc',
      'symbol': 'GNF',
      'country': 'Guinea',
    },
    {
      'currencyId': 'GYD',
      'name': 'Guyana Dollar',
      'symbol': 'GYD',
      'country': 'Guyana',
    },
    {
      'currencyId': 'HTG',
      'name': 'Gourde',
      'symbol': 'HTG',
      'country': 'Haiti',
    },
    {
      'currencyId': 'HNL',
      'name': 'Lempira',
      'symbol': 'HNL',
      'country': 'Honduras',
    },
    {
      'currencyId': 'HKD',
      'name': 'Hong Kong Dollar',
      'symbol': 'HKD',
      'country': 'Hong Kong',
    },
    {
      'currencyId': 'HUF',
      'name': 'Forint',
      'symbol': 'HUF',
      'country': 'Hungary',
    },
    {
      'currencyId': 'ISK',
      'name': 'Iceland Krona',
      'symbol': 'ISK',
      'country': 'Iceland',
    },
    {
      'currencyId': 'INR',
      'name': 'Indian Rupee',
      'symbol': 'INR',
      'country': 'India',
    },
    {
      'currencyId': 'IDR',
      'name': 'Rupiah',
      'symbol': 'IDR',
      'country': 'Indonesia',
    },
    {
      'currencyId': 'IRR',
      'name': 'Iranian Rial',
      'symbol': 'IRR',
      'country': 'Iran',
    },
    {
      'currencyId': 'IQD',
      'name': 'Iraqi Dinar',
      'symbol': 'IQD',
      'country': 'Iraq',
    },
    {
      'currencyId': 'ILS',
      'name': 'New Israeli Shekel',
      'symbol': 'ILS',
      'country': 'Israel',
    },
    {
      'currencyId': 'JMD',
      'name': 'Jamaican Dollar',
      'symbol': 'JMD',
      'country': 'Jamaica',
    },
    {'currencyId': 'JPY', 'name': 'Yen', 'symbol': 'JPY', 'country': 'Japan'},
    {
      'currencyId': 'JOD',
      'name': 'Jordanian Dinar',
      'symbol': 'JOD',
      'country': 'Jordan',
    },
    {
      'currencyId': 'KZT',
      'name': 'Tenge',
      'symbol': 'KZT',
      'country': 'Kazakhstan',
    },
    {
      'currencyId': 'KES',
      'name': 'Kenyan Shilling',
      'symbol': 'KES',
      'country': 'Kenya',
    },
    {
      'currencyId': 'KWD',
      'name': 'Kuwaiti Dinar',
      'symbol': 'KWD',
      'country': 'Kuwait',
    },
    {
      'currencyId': 'LAK',
      'name': 'Lao Kip',
      'symbol': 'LAK',
      'country': 'Laos',
    },
    {
      'currencyId': 'LBP',
      'name': 'Lebanese Pound',
      'symbol': 'LBP',
      'country': 'Lebanon',
    },
    {
      'currencyId': 'LSL',
      'name': 'Loti',
      'symbol': 'LSL',
      'country': 'Lesotho',
    },
    {
      'currencyId': 'LRD',
      'name': 'Liberian Dollar',
      'symbol': 'LRD',
      'country': 'Liberia',
    },
    {
      'currencyId': 'LYD',
      'name': 'Libyan Dinar',
      'symbol': 'LYD',
      'country': 'Libya',
    },
    {
      'currencyId': 'MYR',
      'name': 'Malaysian Ringgit',
      'symbol': 'MYR',
      'country': 'Malaysia',
    },
    {
      'currencyId': 'MVR',
      'name': 'Rufiyaa',
      'symbol': 'MVR',
      'country': 'Maldives',
    },
    {
      'currencyId': 'MXN',
      'name': 'Mexican Peso',
      'symbol': 'MXN',
      'country': 'Mexico',
    },
    {
      'currencyId': 'MDL',
      'name': 'Moldovan Leu',
      'symbol': 'MDL',
      'country': 'Moldova',
    },
    {
      'currencyId': 'MNT',
      'name': 'Tugrik',
      'symbol': 'MNT',
      'country': 'Mongolia',
    },
    {
      'currencyId': 'MAD',
      'name': 'Moroccan Dirham',
      'symbol': 'MAD',
      'country': 'Morocco',
    },
    {
      'currencyId': 'MMK',
      'name': 'Kyat',
      'symbol': 'MMK',
      'country': 'Myanmar',
    },
    {
      'currencyId': 'NAD',
      'name': 'Namibian Dollar',
      'symbol': 'NAD',
      'country': 'Namibia',
    },
    {
      'currencyId': 'NPR',
      'name': 'Nepalese Rupee',
      'symbol': 'NPR',
      'country': 'Nepal',
    },
    {
      'currencyId': 'NZD',
      'name': 'New Zealand Dollar',
      'symbol': 'NZD',
      'country': 'New Zealand',
    },
    {
      'currencyId': 'NGN',
      'name': 'Naira',
      'symbol': 'NGN',
      'country': 'Nigeria',
    },
    {
      'currencyId': 'KPW',
      'name': 'North Korean Won',
      'symbol': 'KPW',
      'country': 'North Korea',
    },
    {
      'currencyId': 'NOK',
      'name': 'Norwegian Krone',
      'symbol': 'NOK',
      'country': 'Norway',
    },
    {
      'currencyId': 'OMR',
      'name': 'Omani Rial',
      'symbol': 'OMR',
      'country': 'Oman',
    },
    {
      'currencyId': 'PKR',
      'name': 'Pakistan Rupee',
      'symbol': 'PKR',
      'country': 'Pakistan',
    },
    {
      'currencyId': 'PAB',
      'name': 'Balboa',
      'symbol': 'PAB',
      'country': 'Panama',
    },
    {
      'currencyId': 'PYG',
      'name': 'Guarani',
      'symbol': 'PYG',
      'country': 'Paraguay',
    },
    {'currencyId': 'PEN', 'name': 'Sol', 'symbol': 'PEN', 'country': 'Peru'},
    {
      'currencyId': 'PHP',
      'name': 'Philippine Peso',
      'symbol': 'PHP',
      'country': 'Philippines',
    },
    {
      'currencyId': 'PLN',
      'name': 'Zloty',
      'symbol': 'PLN',
      'country': 'Poland',
    },
    {
      'currencyId': 'QAR',
      'name': 'Qatari Riyal',
      'symbol': 'QAR',
      'country': 'Qatar',
    },
    {
      'currencyId': 'RON',
      'name': 'Romanian Leu',
      'symbol': 'RON',
      'country': 'Romania',
    },
    {
      'currencyId': 'RUB',
      'name': 'Russian Ruble',
      'symbol': 'RUB',
      'country': 'Russia',
    },
    {
      'currencyId': 'RWF',
      'name': 'Rwandan Franc',
      'symbol': 'RWF',
      'country': 'Rwanda',
    },
    {
      'currencyId': 'SAR',
      'name': 'Saudi Riyal',
      'symbol': 'SAR',
      'country': 'Saudi Arabia',
    },
    {
      'currencyId': 'RSD',
      'name': 'Serbian Dinar',
      'symbol': 'RSD',
      'country': 'Serbia',
    },
    {
      'currencyId': 'SGD',
      'name': 'Singapore Dollar',
      'symbol': 'SGD',
      'country': 'Singapore',
    },
    {
      'currencyId': 'ZAR',
      'name': 'Rand',
      'symbol': 'ZAR',
      'country': 'South Africa',
    },
    {
      'currencyId': 'KRW',
      'name': 'Won',
      'symbol': 'KRW',
      'country': 'South Korea',
    },
    {
      'currencyId': 'LKR',
      'name': 'Sri Lankan Rupee',
      'symbol': 'LKR',
      'country': 'Sri Lanka',
    },
    {
      'currencyId': 'SDG',
      'name': 'Sudanese Pound',
      'symbol': 'SDG',
      'country': 'Sudan',
    },
    {
      'currencyId': 'SEK',
      'name': 'Swedish Krona',
      'symbol': 'SEK',
      'country': 'Sweden',
    },
    {
      'currencyId': 'CHF',
      'name': 'Swiss Franc',
      'symbol': 'CHF',
      'country': 'Switzerland',
    },
    {
      'currencyId': 'SYP',
      'name': 'Syrian Pound',
      'symbol': 'SYP',
      'country': 'Syria',
    },
    {
      'currencyId': 'TWD',
      'name': 'New Taiwan Dollar',
      'symbol': 'TWD',
      'country': 'Taiwan',
    },
    {
      'currencyId': 'TZS',
      'name': 'Tanzanian Shilling',
      'symbol': 'TZS',
      'country': 'Tanzania',
    },
    {
      'currencyId': 'THB',
      'name': 'Baht',
      'symbol': 'THB',
      'country': 'Thailand',
    },
    {
      'currencyId': 'TND',
      'name': 'Tunisian Dinar',
      'symbol': 'TND',
      'country': 'Tunisia',
    },
    {
      'currencyId': 'TRY',
      'name': 'Turkish Lira',
      'symbol': 'TRY',
      'country': 'Turkey',
    },
    {
      'currencyId': 'UGX',
      'name': 'Ugandan Shilling',
      'symbol': 'UGX',
      'country': 'Uganda',
    },
    {
      'currencyId': 'UAH',
      'name': 'Hryvnia',
      'symbol': 'UAH',
      'country': 'Ukraine',
    },
    {
      'currencyId': 'AED',
      'name': 'UAE Dirham',
      'symbol': 'AED',
      'country': 'United Arab Emirates',
    },
    {
      'currencyId': 'GBP',
      'name': 'Pound Sterling',
      'symbol': 'GBP',
      'country': 'United Kingdom',
    },
    {
      'currencyId': 'UYU',
      'name': 'Uruguayan Peso',
      'symbol': 'UYU',
      'country': 'Uruguay',
    },
    {
      'currencyId': 'UZS',
      'name': 'Uzbek Som',
      'symbol': 'UZS',
      'country': 'Uzbekistan',
    },
    {
      'currencyId': 'VES',
      'name': 'Bolivar Soberano',
      'symbol': 'VES',
      'country': 'Venezuela',
    },
    {
      'currencyId': 'VND',
      'name': 'Dong',
      'symbol': 'VND',
      'country': 'Vietnam',
    },
    {
      'currencyId': 'YER',
      'name': 'Yemeni Rial',
      'symbol': 'YER',
      'country': 'Yemen',
    },
    {
      'currencyId': 'ZMW',
      'name': 'Zambian Kwacha',
      'symbol': 'ZMW',
      'country': 'Zambia',
    },
    {
      'currencyId': 'ZWL',
      'name': 'Zimbabwe Dollar',
      'symbol': 'ZWL',
      'country': 'Zimbabwe',
    },
  ];
}
