import 'package:flutter/material.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

class SavingGoalConfirmationScreen extends StatefulWidget {
  final String userId;
  final Map<String, dynamic> plan;
  final Map<String, dynamic> feasibility;
  final Map<String, dynamic> accountSuggestions;
  final List<Map<String, dynamic>> accounts;

  const SavingGoalConfirmationScreen({
    super.key,
    required this.userId,
    required this.plan,
    required this.feasibility,
    required this.accountSuggestions,
    required this.accounts,
  });

  @override
  State<SavingGoalConfirmationScreen> createState() =>
      _SavingGoalConfirmationScreenState();
}

class _SavingGoalConfirmationScreenState
    extends State<SavingGoalConfirmationScreen> {
  late String? _selectedSourceAccountId;
  late String? _selectedDestAccountId;
  bool _isCreating = false;

  @override
  void initState() {
    super.initState();
    _selectedSourceAccountId =
        widget.accountSuggestions['suggestedSourceAccountId'];
    _selectedDestAccountId =
        widget.accountSuggestions['suggestedDestAccountId'];
  }

  Future<void> _createSavingGoal() async {
    if (_selectedSourceAccountId == null || _selectedDestAccountId == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please select both source and destination accounts'),
        ),
      );
      return;
    }

    setState(() {
      _isCreating = true;
    });

    try {
      // Generate sequential ID
      final response = await Supabase.instance.client
          .from('SavingGoal')
          .select('goalId')
          .eq('userId', widget.userId)
          .order('goalId', ascending: false)
          .limit(1);

      int nextNumber = 1;
      if (response.isNotEmpty) {
        final lastGoalId = response[0]['goalId'] as String;
        final prefixLength = 'SAVG'.length + widget.userId.length;
        if (lastGoalId.length > prefixLength) {
          final lastNumberStr = lastGoalId.substring(prefixLength);
          final lastNumber = int.tryParse(lastNumberStr) ?? 0;
          nextNumber = lastNumber + 1;
        }
      }
      final goalId =
          'SAVG${widget.userId}${nextNumber.toString().padLeft(4, '0')}';

      print('Generated Goal ID: $goalId');

      // Insert the saving goal
      await Supabase.instance.client.from('SavingGoal').insert({
        'goalId': goalId,
        'name': widget.plan['savingGoalName'],
        'type': 'intelligent',
        'targetAmount': widget.plan['targetAmount'],
        'currentAmount': 0,
        'startDate': widget.plan['startDate'],
        'endDate': widget.plan['endDate'],
        'description': 'Generated by Intelligent Savings Goal Assistant',
        'status': 'active',
        'cycleStatus': false,
        'cycleFrequency': null,
        'icon': null,
        'sourceAcountId': _selectedSourceAccountId,
        'destAccountId': _selectedDestAccountId,
        'linkedAccountId': _selectedDestAccountId,
        'userId': widget.userId,
      });

      if (mounted) {
        // Show success dialog
        showDialog(
          context: context,
          barrierDismissible: false,
          builder: (BuildContext context) {
            return Dialog(
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(20),
              ),
              backgroundColor: const Color(0xFFFFF9E6),
              child: Container(
                padding: const EdgeInsets.all(24),
                decoration: BoxDecoration(
                  color: const Color(0xFFFFF9E6),
                  borderRadius: BorderRadius.circular(20),
                  border: Border.all(color: const Color(0xFFFFE5B4), width: 2),
                ),
                child: Column(
                  mainAxisSize: MainAxisSize.min,
                  children: [
                    // Success icon
                    Container(
                      width: 60,
                      height: 60,
                      decoration: BoxDecoration(
                        shape: BoxShape.circle,
                        color: const Color(0xFFA7E399),
                      ),
                      child: const Icon(
                        Icons.check,
                        color: Colors.white,
                        size: 32,
                      ),
                    ),
                    const SizedBox(height: 20),
                    // Success title
                    const Text(
                      'Goal Created Successfully!',
                      textAlign: TextAlign.center,
                      style: TextStyle(
                        fontSize: 20,
                        fontWeight: FontWeight.bold,
                        color: Color(0xFFF39C12),
                      ),
                    ),
                    const SizedBox(height: 12),
                    // Success message
                    Text(
                      'Your saving goal "${widget.plan['savingGoalName']}" has been created. Start saving towards your goal!',
                      textAlign: TextAlign.center,
                      style: const TextStyle(
                        fontSize: 14,
                        color: Color(0xFF666666),
                      ),
                    ),
                    const SizedBox(height: 24),
                    // Done button
                    SizedBox(
                      width: double.infinity,
                      height: 48,
                      child: ElevatedButton(
                        onPressed: () {
                          Navigator.pop(context); // Close dialog
                          // Navigate back to savings page and refresh
                          Navigator.of(context).popUntil(
                            (route) =>
                                route.isFirst ||
                                route.settings.name == 'savings',
                          );
                          Navigator.pop(context, true);
                        },
                        style: ElevatedButton.styleFrom(
                          backgroundColor: const Color(0xFFA7E399),
                          foregroundColor: Colors.white,
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(10),
                          ),
                          textStyle: const TextStyle(
                            fontSize: 16,
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                        child: const Text('View My Goals'),
                      ),
                    ),
                  ],
                ),
              ),
            );
          },
        );
      }
    } catch (e) {
      print('Error creating saving goal: $e');
      if (mounted) {
        ScaffoldMessenger.of(
          context,
        ).showSnackBar(SnackBar(content: Text('Error creating goal: $e')));
      }
    } finally {
      setState(() {
        _isCreating = false;
      });
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: const Color(0xFFFFFFFB),
      appBar: AppBar(
        backgroundColor: const Color(0xFFFFFFFB),
        elevation: 0,
        leading: GestureDetector(
          onTap: () => Navigator.pop(context),
          child: const Icon(Icons.arrow_back, color: Colors.black),
        ),
        title: const Text(
          'Confirm Your Goal',
          style: TextStyle(
            color: Colors.black,
            fontSize: 20,
            fontWeight: FontWeight.bold,
          ),
        ),
        centerTitle: false,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Goal Details Summary
            Text(
              'Goal Details',
              style: TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.bold,
                color: Colors.grey.shade800,
              ),
            ),
            const SizedBox(height: 12),
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: Colors.green.shade50,
                borderRadius: BorderRadius.circular(12),
              ),
              child: Column(
                children: [
                  _buildDetailRow(
                    'Goal Name',
                    widget.plan['savingGoalName'] ?? '',
                  ),
                  const SizedBox(height: 12),
                  _buildDetailRow(
                    'Target Amount',
                    'RM${(widget.plan['targetAmount'] ?? 0).toStringAsFixed(2)}',
                  ),
                  const SizedBox(height: 12),
                  _buildDetailRow('Start Date', widget.plan['startDate'] ?? ''),
                  const SizedBox(height: 12),
                  _buildDetailRow('End Date', widget.plan['endDate'] ?? ''),
                  const SizedBox(height: 12),
                  _buildDetailRow(
                    'Duration',
                    '${widget.plan['totalMonths']} months',
                  ),
                  const SizedBox(height: 12),
                  _buildDetailRow(
                    'Monthly Savings',
                    'RM${(widget.plan['monthlyNetSavings'] ?? 0).toStringAsFixed(2)}',
                  ),
                ],
              ),
            ),
            const SizedBox(height: 24),
            // Account Selection Section
            Text(
              'Select Accounts',
              style: TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.bold,
                color: Colors.grey.shade800,
              ),
            ),
            const SizedBox(height: 12),
            // Source Account
            Text(
              'Source Account (Transfer from)',
              style: TextStyle(
                fontSize: 14,
                fontWeight: FontWeight.w600,
                color: Colors.black87,
              ),
            ),
            const SizedBox(height: 8),
            Container(
              decoration: BoxDecoration(
                color: Colors.green.shade100,
                borderRadius: BorderRadius.circular(12),
                border: Border.all(color: Colors.green.shade300),
              ),
              child: DropdownButton<String>(
                value: _selectedSourceAccountId,
                onChanged: (String? newValue) {
                  setState(() {
                    _selectedSourceAccountId = newValue;
                  });
                },
                isExpanded: true,
                underline: const SizedBox(),
                items: widget.accounts.map<DropdownMenuItem<String>>((account) {
                  final accountId = account['accountId'] as String?;
                  final accountName = account['accountName'] as String?;
                  final balance = (account['balance'] ?? 0).toDouble();
                  return DropdownMenuItem<String>(
                    value: accountId,
                    child: Padding(
                      padding: const EdgeInsets.symmetric(
                        horizontal: 12,
                        vertical: 8,
                      ),
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Text(
                            accountName ?? 'Unknown',
                            style: const TextStyle(fontWeight: FontWeight.w500),
                          ),
                          Text(
                            'RM${balance.toStringAsFixed(2)}',
                            style: TextStyle(
                              color: Colors.grey.shade600,
                              fontSize: 12,
                            ),
                          ),
                        ],
                      ),
                    ),
                  );
                }).toList(),
              ),
            ),
            const SizedBox(height: 20),
            // Destination Account
            Text(
              'Destination Account (Save to)',
              style: TextStyle(
                fontSize: 14,
                fontWeight: FontWeight.w600,
                color: Colors.black87,
              ),
            ),
            const SizedBox(height: 8),
            Container(
              decoration: BoxDecoration(
                color: Colors.green.shade100,
                borderRadius: BorderRadius.circular(12),
                border: Border.all(color: Colors.green.shade300),
              ),
              child: DropdownButton<String>(
                value: _selectedDestAccountId,
                onChanged: (String? newValue) {
                  setState(() {
                    _selectedDestAccountId = newValue;
                  });
                },
                isExpanded: true,
                underline: const SizedBox(),
                items: widget.accounts.map<DropdownMenuItem<String>>((account) {
                  final accountId = account['accountId'] as String?;
                  final accountName = account['accountName'] as String?;
                  final balance = (account['balance'] ?? 0).toDouble();
                  return DropdownMenuItem<String>(
                    value: accountId,
                    child: Padding(
                      padding: const EdgeInsets.symmetric(
                        horizontal: 12,
                        vertical: 8,
                      ),
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceBetween,
                        children: [
                          Text(
                            accountName ?? 'Unknown',
                            style: const TextStyle(fontWeight: FontWeight.w500),
                          ),
                          Text(
                            'RM${balance.toStringAsFixed(2)}',
                            style: TextStyle(
                              color: Colors.grey.shade600,
                              fontSize: 12,
                            ),
                          ),
                        ],
                      ),
                    ),
                  );
                }).toList(),
              ),
            ),
            const SizedBox(height: 24),
            // Info Box
            Container(
              padding: const EdgeInsets.all(14),
              decoration: BoxDecoration(
                color: Colors.blue.shade50,
                borderRadius: BorderRadius.circular(12),
                border: Border.all(color: Colors.blue.shade200),
              ),
              child: Row(
                children: [
                  Icon(
                    Icons.lightbulb_outline,
                    color: Colors.blue.shade600,
                    size: 20,
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Text(
                      widget.accountSuggestions['suggestedSourceAccountName'] !=
                              null
                          ? 'AI suggests ${widget.accountSuggestions['suggestedSourceAccountName']} as source and ${widget.accountSuggestions['suggestedDestAccountName']} as destination'
                          : 'Choose suitable accounts for your saving goal',
                      style: TextStyle(
                        color: Colors.blue.shade700,
                        fontSize: 13,
                        height: 1.4,
                      ),
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 28),
            // Action Buttons
            SizedBox(
              width: double.infinity,
              child: ElevatedButton(
                onPressed: _isCreating ? null : _createSavingGoal,
                style: ElevatedButton.styleFrom(
                  backgroundColor: Colors.amber,
                  padding: const EdgeInsets.symmetric(vertical: 14),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                ),
                child: _isCreating
                    ? const Row(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          SizedBox(
                            width: 20,
                            height: 20,
                            child: CircularProgressIndicator(strokeWidth: 2),
                          ),
                          SizedBox(width: 12),
                          Text(
                            'Creating Goal...',
                            style: TextStyle(
                              color: Colors.black,
                              fontWeight: FontWeight.bold,
                            ),
                          ),
                        ],
                      )
                    : const Text(
                        'Create Goal',
                        style: TextStyle(
                          color: Colors.black,
                          fontWeight: FontWeight.bold,
                          fontSize: 16,
                        ),
                      ),
              ),
            ),
            const SizedBox(height: 12),
            SizedBox(
              width: double.infinity,
              child: OutlinedButton(
                onPressed: () => Navigator.pop(context),
                style: OutlinedButton.styleFrom(
                  padding: const EdgeInsets.symmetric(vertical: 14),
                  side: const BorderSide(color: Colors.green),
                  shape: RoundedRectangleBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                ),
                child: const Text(
                  'Back',
                  style: TextStyle(
                    color: Colors.green,
                    fontWeight: FontWeight.bold,
                    fontSize: 16,
                  ),
                ),
              ),
            ),
            const SizedBox(height: 20),
          ],
        ),
      ),
    );
  }

  Widget _buildDetailRow(String label, String value) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(
          label,
          style: TextStyle(color: Colors.grey.shade700, fontSize: 14),
        ),
        Text(
          value,
          style: const TextStyle(
            fontWeight: FontWeight.bold,
            fontSize: 14,
            color: Colors.black,
          ),
        ),
      ],
    );
  }
}
